server:
  port: 8080

spring:
  application:
    name: springboot-security-demo
  main:
    allow-circular-references: true

logging:
  level:
    com.example.springbootsecuritydemo: DEBUG
    org.springframework.security: DEBUG
